"""
Django settings for factly_backend project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import ipaddress

# Load environment variables from .env if present
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() in ('1', 'true', 'yes')

# SECURITY WARNING: keep the secret key used in production secret!
_secret_key = os.getenv('DJANGO_SECRET_KEY')
if not _secret_key:
    # Use a default key only in DEBUG mode for development convenience
    if DEBUG:
        _secret_key = 'django-insecure-dev-only-key-do-not-use-in-production'
    else:
        raise ValueError("DJANGO_SECRET_KEY environment variable must be set in production")
SECRET_KEY = _secret_key

# Configure allowed hosts via environment variable (comma-separated). Default: allow localhost for development.
# If no ALLOWED_HOSTS is set, default to localhost and 127.0.0.1 for development.
_allowed = os.getenv('ALLOWED_HOSTS', '')
ALLOWED_HOSTS = [_h.strip() for _h in _allowed.split(',') if _h.strip()] if _allowed else ['localhost', '127.0.0.1', 'testserver', '0.0.0.0']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'verification',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'factly_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'factly_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validation

# =============================================================================
# CELERY CONFIGURATION - Distributed Task Processing
# =============================================================================

# Broker Configuration (Redis Cluster)
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://localhost:6379/1')

# Serialization
CELERY_ACCEPT_CONTENT = ['json', 'msgpack']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

# Timezone
CELERY_TIMEZONE = 'UTC'
CELERY_ENABLE_UTC = True

# Task Execution Settings
CELERY_TASK_ALWAYS_EAGER = False  # Never run tasks synchronously in production
CELERY_TASK_STORE_EAGER_RESULT = False
CELERY_TASK_IGNORE_RESULT = False
CELERY_TASK_TRACK_STARTED = True

# Time Limits (prevent runaway tasks)
CELERY_TASK_TIME_LIMIT = 600  # 10 minutes hard limit
CELERY_TASK_SOFT_TIME_LIMIT = 540  # 9 minutes soft limit (gives 1min cleanup)

# Task Acknowledgment (ensure tasks don't get lost)
CELERY_TASK_ACKS_LATE = True  # Ack after task completes, not before
CELERY_TASK_REJECT_ON_WORKER_LOST = True  # Requeue if worker dies

# Rate Limiting (prevent overwhelming external APIs)
CELERY_TASK_DEFAULT_RATE_LIMIT = '100/s'

# Worker Concurrency (auto-detect CPU cores)
CELERY_WORKER_CONCURRENCY = int(os.getenv('CELERY_WORKER_CONCURRENCY', '4'))
CELERY_WORKER_PREFETCH_MULTIPLIER = 1  # Better for long-running tasks
CELERY_WORKER_MAX_TASKS_PER_CHILD = 1000  # Restart workers to prevent memory leaks
CELERY_WORKER_MAX_MEMORY_PER_CHILD = 250000  # 250MB (restart if exceeded)

# Result Backend Settings
CELERY_RESULT_EXPIRES = 86400  # 24 hours
CELERY_RESULT_EXTENDED = True

# Broker Connection Retry
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_BROKER_CONNECTION_MAX_RETRIES = 10
CELERY_BROKER_CONNECTION_TIMEOUT = 30

# Redis-Specific Settings
CELERY_BROKER_TRANSPORT_OPTIONS = {
    'visibility_timeout': 43200,  # 12 hours (tasks must complete within this)
    'queue_order_strategy': 'priority',
    'master_name': 'factly-redis-master',  # For Redis Sentinel
}

# Redis Result Backend Transport
CELERY_RESULT_BACKEND_TRANSPORT_OPTIONS = {
    'retry_on_timeout': True,
    'socket_connect_timeout': 30,
    'socket_timeout': 30,
}

# Task Routes (direct tasks to specific queues)
CELERY_TASK_ROUTES = {
    'services.tasks.verification.*': {'queue': 'verification'},
    'services.tasks.ingestion.*': {'queue': 'ingestion'},
    'services.tasks.analysis.*': {'queue': 'analysis'},
    'services.tasks.high_priority.*': {'queue': 'high_priority'},
    'services.tasks.low_priority.*': {'queue': 'low_priority'},
}

# Default Queue
CELERY_TASK_DEFAULT_QUEUE = 'default'

# =============================================================================
# CACHE CONFIGURATION - Local Memory Cache (Development)
# =============================================================================

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
        'TIMEOUT': 300,
        'OPTIONS': {
            'MAX_ENTRIES': 1000
        }
    },
    'verification_results': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'verification-results',
        'TIMEOUT': 86400,  # 24 hours
    },
    'session_cache': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'session-cache',
        'TIMEOUT': 3600,  # 1 hour
    },
}

# Session Configuration
SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
SESSION_CACHE_ALIAS = 'default'

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
    'EXCEPTION_HANDLER': 'factly_backend.exception_handlers.custom_exception_handler',
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '60/minute',
        'user': '120/minute',
        'login': '10/minute',
        'password_reset': '5/minute',
    },
}

# Custom exception handler for better error responses
def custom_exception_handler(exc, context):
    """
    Custom exception handler that returns proper error messages
    instead of generic 500 Internal Server Errors.
    """
    from rest_framework.views import exception_handler
    from rest_framework.response import Response
    from rest_framework import status
    import traceback
    
    # Call REST framework's default exception handler
    response = exception_handler(exc, context)
    
    # If response is None, an unhandled exception occurred
    if response is None:
        # Get the view and request for logging
        view = context.get('view')
        request = context.get('request')
        
        # Log the full exception with stack trace
        logger.error(
            f"Unhandled exception in {view}: {exc}",
            exc_info=True,
            extra={
                'request': str(request) if request else 'No request',
                'traceback': traceback.format_exc()
            }
        )
        
        # Determine appropriate status code based on exception type
        if isinstance(exc, ValueError):
            status_code = status.HTTP_400_BAD_REQUEST
            error_message = str(exc)
        elif isinstance(exc, KeyError):
            status_code = status.HTTP_400_BAD_REQUEST
            error_message = f"Missing required field: {str(exc)}"
        else:
            status_code = status.HTTP_500_INTERNAL_SERVER_ERROR
            # In DEBUG mode, show the actual error; in production, show generic message
            if DEBUG:
                error_message = f"{exc.__class__.__name__}: {str(exc)}"
            else:
                error_message = "An unexpected error occurred. Please try again later."
        
        response = Response(
            {'error': error_message},
            status=status_code
        )
    
    return response

# JWT Settings for djangorestframework-simplejwt
from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),  # Access token expires in 60 minutes
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),       # Refresh token valid for 7 days
    'ROTATE_REFRESH_TOKENS': True,                     # Issue new refresh token on each refresh
    'BLACKLIST_AFTER_ROTATION': True,                 # Blacklist old refresh tokens
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',
    'JTI_CLAIM': 'jti',
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),  # Sliding token refresh lifetime
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=60),       # Sliding token lifetime
    'SLIDING_TOKEN_REFRESH_LIFETIME_GRACE_PERIOD': timedelta(minutes=5),
}

# Security-related settings
# Limit upload sizes to mitigate DoS via large payloads
DATA_UPLOAD_MAX_MEMORY_SIZE = int(os.getenv('DATA_UPLOAD_MAX_MEMORY_SIZE', 5 * 1024 * 1024))  # 5 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = int(os.getenv('FILE_UPLOAD_MAX_MEMORY_SIZE', 5 * 1024 * 1024))  # 5 MB

# Production-only security flags (toggle via env)
SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'False').lower() in ('1', 'true', 'yes')
SESSION_COOKIE_SECURE = os.getenv('SESSION_COOKIE_SECURE', 'False').lower() in ('1', 'true', 'yes')
CSRF_COOKIE_SECURE = os.getenv('CSRF_COOKIE_SECURE', 'False').lower() in ('1', 'true', 'yes')
X_FRAME_OPTIONS = os.getenv('X_FRAME_OPTIONS', 'DENY')

# Additional security headers
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_SECURITY_POLICY = {
    "default-src": ("'self'",),
    "script-src": ("'self'",),
    "style-src": ("'self'", "'unsafe-inline'"),  # unsafe-inline needed for inline styles if any
    "img-src": ("'self'", "data:", "https:"),
    "font-src": ("'self'",),
    "connect-src": ("'self'", "http://localhost:8000"),
    "frame-ancestors": ("'none'",),
}

# Email configuration for password reset and notifications
# Use custom fallback backend that handles invalid credentials gracefully
# In production, use: verification.email_backend.FallbackEmailBackend
# For development only: verification.email_backend.DevelopmentEmailBackend
# For file-based: django.core.mail.backends.filebased.EmailBackend
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'verification.email_backend.FallbackEmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() in ('1', 'true', 'yes')
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
EMAIL_FILE_PATH = os.getenv('EMAIL_FILE_PATH', os.path.join(BASE_DIR, 'tmp', 'emails'))
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@factly.com')

# Password reset token expiration time (in hours)
PASSWORD_RESET_TIMEOUT_HOURS = int(os.getenv('PASSWORD_RESET_TIMEOUT_HOURS', 24))

# Frontend URL for password reset links
FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:3000')

# CORS configuration: enable and set origins via ALLOWED_CORS env variable (comma-separated)
# Default: allow localhost for development only
_allowed_cors = os.getenv('ALLOWED_CORS', 'http://localhost:3000,http://127.0.0.1:3000')
CORS_ALLOWED_ORIGINS = [o.strip() for o in _allowed_cors.split(',') if o.strip()] if _allowed_cors else []
# For development, allow all origins (remove in production)
CORS_ALLOW_ALL_ORIGINS = os.getenv('CORS_ALLOW_ALL_ORIGINS', 'False').lower() == 'true'
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'Access-Control-Allow-Origin',
]

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'factly.log'),
            'formatter': 'verbose',
            'maxBytes': 10 * 1024 * 1024,  # 10MB
            'backupCount': 5,
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'services': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}