@echo off
cd /d "C:\Users\DELL\OneDrive\Desktop\Factly\backend"
echo Running migrations...
call venv\Scripts\python.exe manage.py migrate --noinput
echo Starting Django backend server on port 8000...
call venv\Scripts\python.exe manage.py runserver 0.0.0.0:8000 --noreload
