# Generated by Django 6.0.3 on 2026-07-01 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0002_verificationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationlog',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='verificationlog',
            name='classification',
            field=models.CharField(choices=[('true', 'True'), ('mostly_true', 'Mostly True'), ('half_true', 'Half True'), ('misleading', 'Misleading'), ('false', 'False'), ('unverifiable', 'Unverifiable'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
    ]
