# Generated by Django 6.0.1 on 2026-05-20 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_imported',
            field=models.BooleanField(default=False, help_text='Auto-imported from RSS feed'),
        ),
        migrations.AddField(
            model_name='article',
            name='source_name',
            field=models.CharField(blank=True, help_text='Source attribution name', max_length=200),
        ),
        migrations.AddField(
            model_name='article',
            name='source_url',
            field=models.URLField(blank=True, default=None, help_text='Original URL if imported from RSS', null=True),
        ),
        migrations.CreateModel(
            name='FeedSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('feed_url', models.URLField(help_text='RSS or Atom feed URL', unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('import_interval', models.IntegerField(default=60, help_text='Minutes between import attempts')),
                ('last_imported_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, help_text='Default category for imported articles', null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.category')),
            ],
            options={
                'verbose_name': 'Feed Source',
                'verbose_name_plural': 'Feed Sources',
                'ordering': ['name'],
            },
        ),
    ]
