# Generated by Django 6.0.3 on 2026-07-27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_article_deleted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=350, unique=True)),
                ('summary', models.TextField()),
                ('current_status', models.TextField(blank=True)),
                ('featured_image', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='content.category')),
            ],
            options={
                'verbose_name_plural': 'stories',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyStoryEdition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edition_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled')], default='draft', max_length=10)),
                ('selection_type', models.CharField(choices=[('editorial', 'Editorial'), ('automatic', 'Automatic')], default='editorial', max_length=10)),
                ('selection_reason', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_editions', to='content.story')),
            ],
            options={
                'ordering': ['-edition_date'],
            },
        ),
        migrations.CreateModel(
            name='StoryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(help_text='Order in the reader timeline, starting at 1')),
                ('occurred_at', models.DateTimeField()),
                ('title', models.CharField(max_length=300)),
                ('summary', models.TextField()),
                ('source_url', models.URLField()),
                ('source_name', models.CharField(max_length=200)),
                ('source_published_at', models.DateTimeField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='story_events', to='content.article')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='content.story')),
            ],
            options={
                'ordering': ['position', 'occurred_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='dailystoryedition',
            constraint=models.UniqueConstraint(fields=('edition_date',), name='content_unique_daily_story_edition_date'),
        ),
        migrations.AddConstraint(
            model_name='storyevent',
            constraint=models.UniqueConstraint(fields=('story', 'position'), name='content_unique_story_event_position'),
        ),
    ]
