# Generated by Django 6.0.1 on 2026-07-27 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_daily_story_edition_story_storyevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailystoryedition',
            name='corrected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailystoryedition',
            name='correction_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dailystoryedition',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('fallback', 'Fallback')], default='draft', max_length=10),
        ),
    ]
