# Generated by Django 6.0.1 on 2026-06-23 14:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SourceCredibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=200, unique=True)),
                ('source_url', models.URLField(blank=True)),
                ('platform', models.CharField(max_length=20)),
                ('credibility_score', models.FloatField(default=0.5)),
                ('fact_check_history_count', models.IntegerField(default=0)),
                ('fact_check_accuracy', models.FloatField(default=0.0)),
                ('bias_rating', models.CharField(blank=True, max_length=50)),
                ('factual_reporting', models.CharField(blank=True, max_length=50)),
                ('historical_patterns', models.JSONField(default=dict)),
                ('last_analyzed', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'source_credibility',
                'ordering': ['-credibility_score'],
            },
        ),
        migrations.CreateModel(
            name='TrendSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('platform', models.CharField(choices=[('twitter', 'Twitter/X'), ('reddit', 'Reddit'), ('tiktok', 'TikTok'), ('google_trends', 'Google Trends'), ('bing_trends', 'Bing Trends'), ('news_api', 'News API'), ('rss', 'RSS Feed'), ('custom', 'Custom Source')], max_length=20)),
                ('region', models.CharField(choices=[('global', 'Global'), ('africa', 'Africa'), ('india', 'India'), ('us', 'United States'), ('europe', 'Europe'), ('asia', 'Asia'), ('latin_america', 'Latin America')], default='global', max_length=20)),
                ('api_endpoint', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('rate_limit_per_minute', models.IntegerField(default=60)),
                ('last_fetched', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'trend_sources',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Trend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(db_index=True, max_length=500)),
                ('keywords', models.JSONField(default=list)),
                ('summary', models.TextField(blank=True)),
                ('source_platforms', models.JSONField(default=list)),
                ('source_count', models.IntegerField(default=1)),
                ('engagement_score', models.FloatField(db_index=True, default=0.0)),
                ('engagement_velocity', models.FloatField(default=0.0)),
                ('mention_volume', models.IntegerField(default=0)),
                ('share_count', models.IntegerField(default=0)),
                ('comment_count', models.IntegerField(default=0)),
                ('view_count', models.BigIntegerField(default=0)),
                ('primary_region', models.CharField(default='global', max_length=20)),
                ('detected_regions', models.JSONField(default=list)),
                ('first_detected', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('critical', 'Critical Risk')], default='low', max_length=10)),
                ('misinformation_risk_score', models.FloatField(db_index=True, default=0.0)),
                ('predicted_trend_score', models.FloatField(default=0.0)),
                ('prediction_confidence', models.FloatField(default=0.0)),
                ('prediction_horizon_hours', models.IntegerField(default=24)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('verified', 'Verified'), ('false', 'False Claim'), ('true', 'True Claim'), ('unverifiable', 'Unverifiable')], default='pending', max_length=20)),
                ('factly_score', models.IntegerField(blank=True, null=True)),
                ('verification_summary', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('priority_score', models.FloatField(db_index=True, default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'trends',
                'ordering': ['-priority_score', '-engagement_score'],
                'indexes': [models.Index(fields=['risk_level', '-priority_score'], name='trends_risk_le_cb7040_idx'), models.Index(fields=['verification_status', '-misinformation_risk_score'], name='trends_verific_f98dec_idx')],
            },
        ),
        migrations.CreateModel(
            name='MisinformationAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='active', max_length=20)),
                ('alert_message', models.TextField()),
                ('triggers', models.JSONField(default=list)),
                ('notified_users', models.JSONField(default=list)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('trend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='trend_collector.trend')),
            ],
            options={
                'db_table': 'misinformation_alerts',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrendPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_engagement_24h', models.FloatField(default=0.0)),
                ('predicted_engagement_48h', models.FloatField(default=0.0)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('engagement_acceleration', models.FloatField(default=0.0)),
                ('cross_platform_emergence_score', models.FloatField(default=0.0)),
                ('influencer_amplification_score', models.FloatField(default=0.0)),
                ('sentiment_trajectory', models.CharField(blank=True, max_length=20)),
                ('model_version', models.CharField(default='1.0.0', max_length=50)),
                ('prediction_horizon', models.IntegerField(default=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='trend_collector.trend')),
            ],
            options={
                'db_table': 'trend_predictions',
                'ordering': ['-confidence_score', '-predicted_engagement_48h'],
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_text', models.TextField()),
                ('category', models.CharField(choices=[('health_misinformation', 'Health Misinformation'), ('political_misinformation', 'Political Misinformation'), ('scientific_falsehood', 'Scientific Falsehood'), ('financial_scam', 'Financial Scam'), ('social_falsehood', 'Social Falsehood'), ('unverified', 'Unverified'), ('factual', 'Factual')], default='unverified', max_length=30)),
                ('sentiment', models.CharField(blank=True, max_length=20)),
                ('emotional_language_score', models.FloatField(default=0.0)),
                ('sensationalist_score', models.FloatField(default=0.0)),
                ('source_credibility_score', models.FloatField(default=0.5)),
                ('verified_source_count', models.IntegerField(default=0)),
                ('matches_known_false_claim', models.BooleanField(default=False)),
                ('false_claim_database_match', models.CharField(blank=True, max_length=100)),
                ('claim_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('extracted_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='trend_collector.trend')),
            ],
            options={
                'db_table': 'claims',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category', '-created_at'], name='claims_categor_f4eb04_idx'), models.Index(fields=['matches_known_false_claim', '-emotional_language_score'], name='claims_matches_9af28c_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrendCollectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('items_collected', models.IntegerField(default=0)),
                ('items_new', models.IntegerField(default=0)),
                ('items_deduplicated', models.IntegerField(default=0)),
                ('latency_ms', models.IntegerField(default=0)),
                ('api_success_rate', models.FloatField(default=0.0)),
                ('rate_limit_hits', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='trend_collector.trendsource')),
            ],
            options={
                'db_table': 'trend_collection_logs',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['source', '-started_at'], name='trend_colle_source__764d15_idx'), models.Index(fields=['status', '-started_at'], name='trend_colle_status_37b6fc_idx')],
            },
        ),
    ]
