# Generated by Django 6.0.1 on 2026-07-01 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trend_collector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='source_url',
            field=models.URLField(blank=True, default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='claim',
            name='verdict',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False'), ('misleading', 'Misleading'), ('unverified', 'Unverified'), ('not_verifiable', 'Not Verifiable')], default='unverified', max_length=20),
        ),
        migrations.AlterField(
            model_name='claim',
            name='extracted_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='trend_collector.trend'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='sentiment',
            field=models.CharField(blank=True, choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral'), ('mixed', 'Mixed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sourcecredibility',
            name='bias_rating',
            field=models.CharField(blank=True, choices=[('left', 'Left'), ('center_left', 'Center-Left'), ('center', 'Center'), ('center_right', 'Center-Right'), ('right', 'Right'), ('unknown', 'Unknown')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sourcecredibility',
            name='factual_reporting',
            field=models.CharField(blank=True, choices=[('very_high', 'Very High'), ('high', 'High'), ('mixed', 'Mixed'), ('low', 'Low'), ('very_low', 'Very Low'), ('unknown', 'Unknown')], max_length=20),
        ),
        migrations.AlterField(
            model_name='trendcollectionlog',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial')], max_length=20),
        ),
        migrations.AlterField(
            model_name='trendprediction',
            name='sentiment_trajectory',
            field=models.CharField(blank=True, choices=[('improving', 'Improving'), ('declining', 'Declining'), ('stable', 'Stable')], max_length=20),
        ),
    ]
